name: API CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/cd-api.yaml

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-api:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          flyctl deploy --remote-only
        working-directory: backend
