# fly.toml app configuration file generated for vidrank on 2024-07-03T00:42:54-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vidrank'
primary_region = 'sea'

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'

[mounts]
destination = "/volume"
source = "vidrank"
initial_size = "1gb"
